apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: aneesh-role
  namespace: devops
rules:
  - apiGroups: [ "*" ]
    resources: [ "pods/exec","pods","deployments" ]
    verbs: [ "get", "list","edit","create","update","delete","patch"  ]


---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: aneesh-rb
  namespace: devops
subjects:
- kind: User
  name: aneesh
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: aneesh-role
  apiGroup: rbac.authorization.k8s.io

