---
- hosts: mydc
  become: yes
  remote_user: devops
  tasks:
    - name: install apache on Ubuntu  servers
      apt:
        name: 
          - apache2
          - unzip
          - ntp
        state: present
      when:  ansible_os_family == "Debian" 
    - name: install apache on Centos servers
      yum:
        name: 
          - httpd
          - unzip

        state: installed
      when:  ansible_os_family == "RedHat"
    - name: Start Apache 
      service:
          name: apache2
          state: started
          enabled: yes
    - name: Configure website in remote server
      unarchive:
         src: web.tgz
         dest: /var/www/html/
