apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydep-2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mydep2
  template:
    metadata:
      labels:
        app: mydep2
    spec:
      containers:
      - image: 966145/myserver121:latest
        name: nginx
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
     name: pod-svc2
spec:
   type: NodePort
   selector:
       app: mydep2
   ports:
   - port: 80
     nodePort: 30124


