apiVersion: v1
kind: Pod
metadata:
    name: mypod
    labels:
       app: myapp
    annotations:
       description: testing pod 
spec: 
   containers:
   - name: con1
     image: nginx:latest
     ports:
     - containerPort: 80
     livenessProbe:
        httpGet:
          path: /index.html
          port: 80
        initialDelaySeconds: 15
        periodSeconds: 5
     readinessProbe:
        httpGet:
          path: /index.html
          port: 80
        initialDelaySeconds: 15
        periodSeconds: 5

