apiVersion: v1
kind: Pod
metadata:
    name: mypod
    labels:
       app: myapp
       env: dev
spec: 
   containers:
   - name: con1
     image: nginx:latest
     ports:
     - containerPort: 80
     volumeMounts:
       - name: myvol
         mountPath: /data
   - name: con2
     image: tomcat:latest
     ports:
     - containerPort: 8080
     volumeMounts:
       - name: myvol
         mountPath: /data

   volumes:
     - name: myvol
       hostPath:
          path: /mydata
