apiVersion: batch/v1
kind: Job
metadata:
   name: myjob
spec:
   completions: 10
   parallelism: 2
   template:
       metadata: 
          name: myjob
       spec:
          containers:
          - name: jobcon
            image: nginx:latest
            command: ["echo","hello test"]
          restartPolicy: Never
