apiVersion: v1
kind: Pod
metadata:
   name: mysql
   labels:
      app: mysql
spec:
   containers:
   - name: db
     image: mysql:5.7
     env:
      - name: MYSQL_ROOT_PASSWORD
        valueFrom:
            secretKeyRef:
               name: mycred
               key: password
        
      - name: MYSQL_DATABASE
        value: wordpress
     ports:
     - containerPort: 3306

---
apiVersion: v1
kind: Service
metadata:
   name: mysql-svc
spec:
   selector:
      app: mysql
   ports:
    - port: 3306

---
apiVersion: v1
data:
  password: dGVzdDEyMw==
kind: Secret
metadata:
  creationTimestamp: null
  name: mycred

