apiVersion: v1
kind: Pod
metadata:
    namespace: devops
    name: mypod
    labels:
       app: myapp
       env: dev
spec: 
   containers:
   - name: con1
     image: nginx:latest
     ports:
     - containerPort: 80
   - name: con2
     image: tomcat:latest
     ports:
     - containerPort: 8080
#   nodeName: node2
#   nodeSelector:
#      cpu: intel


