apiVersion: v1
kind: Pod
metadata:
    name: podaff
    labels:
       app: webapp
spec: 
   containers:
   - name: con1
     image: nginx:latest
     ports:
     - containerPort: 80
   - name: con2
     image: tomcat:latest
     ports:
     - containerPort: 8080
   affinity:
     podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
             matchExpressions:
             - key: app
               operator: In
               values:
               - myapp
          topologyKey: "kubernetes.io/hostname"

