apiVersion: v1
kind: ReplicationController
metadata:
     name: myrc
spec:
   replicas: 3
   selector:
      app: myapp
   template:
       metadata:
           labels:
             app: myapp
       spec:
         containers:
         - name: test123
           image: nginx:latest
           ports:
           - containerPort: 80
