apiVersion: v1
kind: ResourceQuota
metadata:
   name: devops-rq
   namespace: devops
spec:
   hard:
     requests.cpu: "1"
     requests.memory: "1Gi"
     limits.cpu: "2"
     limits.memory: "2Gi"
     configmaps: "10"
     secrets: "10"
     services: "5"
     count/pods: "10"
