apiVersion: v1
kind: Pod
metadata:
   name: wordpress
   labels:
      app: wordpress
spec:
   containers:
   - name: wp
     image: wordpress:latest
     envFrom:
      - configMapRef:
           name: myconf
     ports:
     - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
   name: wp-svc
spec:
   type: NodePort
   selector:
      app: wordpress
   ports:
    - port: 80
      nodePort: 30125
---
apiVersion: v1
data:
  WORDPRESS_DB_HOST: mysql-svc
  WORDPRESS_DB_NAME: wordpress
  WORDPRESS_DB_PASSWORD: test123
  WORDPRESS_DB_USER: root
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: myconf

